import * as Types from './axios-client-minimal.types';
export * from './axios-client-minimal.types';

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import type { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export * as Client from './axios-client-minimal/Client';

export * as Query from './axios-client-minimal/Query';



import { addResultTypeFactory } from './axios-client-minimal/helpers';
export { setBaseUrl, getBaseUrl } from './axios-client-minimal/helpers';
export { setAxiosFactory, getAxios } from './axios-client-minimal/helpers';
