//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../magadan.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './DocumentUtilitiesClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';



export function mergeTableCellsUrl(): string {
  let url_ = getBaseUrl() + "/api/document-utilities/merge-table";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function mergeTableCellsMutationKey(): MutationKey {
  return trimArrayEnd([
      'DocumentUtilitiesClient',
      'mergeTableCells',
    ]);
}

export function useMergeTableCellsMutation<TContext>(options?: Omit<UseMutationOptions<string, unknown, Types.MergeTableRequestBody, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<string, unknown, Types.MergeTableRequestBody, TContext> {
  const key = mergeTableCellsMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.MergeTableRequestBody) => Client.mergeTableCells(body),
    mutationKey: key,
  });
}
  
export function insertTableUrl(): string {
  let url_ = getBaseUrl() + "/api/document-utilities/InsertTable";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function insertTableMutationKey(): MutationKey {
  return trimArrayEnd([
      'DocumentUtilitiesClient',
      'insertTable',
    ]);
}

export function useInsertTableMutation<TContext>(options?: Omit<UseMutationOptions<string, unknown, Types.InsertTableRequestBody, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<string, unknown, Types.InsertTableRequestBody, TContext> {
  const key = insertTableMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.InsertTableRequestBody) => Client.insertTable(body),
    mutationKey: key,
  });
}
  
export function getShortenedTableVersionUrl(): string {
  let url_ = getBaseUrl() + "/api/document-utilities/GetShortenedTableVersion";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function getShortenedTableVersionMutationKey(): MutationKey {
  return trimArrayEnd([
      'DocumentUtilitiesClient',
      'getShortenedTableVersion',
    ]);
}

export function useGetShortenedTableVersionMutation<TContext>(options?: Omit<UseMutationOptions<string, unknown, string, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<string, unknown, string, TContext> {
  const key = getShortenedTableVersionMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (variableValue: string) => Client.getShortenedTableVersion(variableValue),
    mutationKey: key,
  });
}
  
export function getTablesPropertiesUrl(): string {
  let url_ = getBaseUrl() + "/api/document-utilities/GetTablesProperties";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function getTablesPropertiesMutationKey(): MutationKey {
  return trimArrayEnd([
      'DocumentUtilitiesClient',
      'getTablesProperties',
    ]);
}

export function useGetTablesPropertiesMutation<TContext>(options?: Omit<UseMutationOptions<Types.SetTablePropertiesInfo[], unknown, Types.GetTableRequestBody, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.SetTablePropertiesInfo[], unknown, Types.GetTableRequestBody, TContext> {
  const key = getTablesPropertiesMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.GetTableRequestBody) => Client.getTablesProperties(body),
    mutationKey: key,
  });
}
  
export function updateDocumentVariablesUrl(): string {
  let url_ = getBaseUrl() + "/api/document-utilities/UpdateDocumentVariables";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function updateDocumentVariablesMutationKey(): MutationKey {
  return trimArrayEnd([
      'DocumentUtilitiesClient',
      'updateDocumentVariables',
    ]);
}

export function useUpdateDocumentVariablesMutation<TContext>(options?: Omit<UseMutationOptions<string, unknown, Types.UpdateDocumentVariablesRequestBody, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<string, unknown, Types.UpdateDocumentVariablesRequestBody, TContext> {
  const key = updateDocumentVariablesMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.UpdateDocumentVariablesRequestBody) => Client.updateDocumentVariables(body),
    mutationKey: key,
  });
}