//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../magadan.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './DocumentExportClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type PrepareDocumentForExportDocumentExportMutationParameters = {
  docFile?: Types.FileParameter | null | undefined ;
}

export type GetPreparedDocumentAsDocxDocumentExportQueryParameters = {
  id?: string | undefined ;
}

export type GetPreparedDocumentAsRtfDocumentExportQueryParameters = {
  id?: string | undefined ;
}

export type GetPreparedDocumentAsPdfDocumentExportQueryParameters = {
  id?: string | undefined ;
}

export type GetExportNameDocumentExportQueryParameters = {
  documentId: number ;
}

export function prepareDocumentForExportUrl(): string {
  let url_ = getBaseUrl() + "/api/document-export/prepare-document";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function prepareDocumentForExportMutationKey(): MutationKey {
  return trimArrayEnd([
      'DocumentExportClient',
      'prepareDocumentForExport',
    ]);
}

/**
 * Sends document to preparation for export. Preparation merges splitted tables
 * @param docFile (optional) 
 */
export function usePrepareDocumentForExportMutation<TContext>(options?: Omit<UseMutationOptions<string, unknown, PrepareDocumentForExportDocumentExportMutationParameters, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<string, unknown, PrepareDocumentForExportDocumentExportMutationParameters, TContext> {
  const key = prepareDocumentForExportMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (prepareDocumentForExportDocumentExportMutationParameters: PrepareDocumentForExportDocumentExportMutationParameters) => Client.prepareDocumentForExport(prepareDocumentForExportDocumentExportMutationParameters.docFile),
    mutationKey: key,
  });
}
  
export function getPreparedDocumentAsDocxUrl(id?: string | undefined): string {
  let url_ = getBaseUrl() + "/api/document-export/prepared-as-docx?";
if (id === null)
    throw new Error("The parameter 'id' cannot be null.");
else if (id !== undefined)
    url_ += "id=" + encodeURIComponent("" + id) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getPreparedDocumentAsDocxDefaultOptions: Omit<UseQueryOptions<Types.FileResponse, unknown, Types.FileResponse>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.FileResponse, unknown, Types.FileResponse>, 'queryFn'>> = {
};
export function getGetPreparedDocumentAsDocxDefaultOptions() {
  return getPreparedDocumentAsDocxDefaultOptions;
};
export function setGetPreparedDocumentAsDocxDefaultOptions(options: typeof getPreparedDocumentAsDocxDefaultOptions) {
  getPreparedDocumentAsDocxDefaultOptions = options;
}

export function getPreparedDocumentAsDocxQueryKey(id?: string | undefined): QueryKey;
export function getPreparedDocumentAsDocxQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as GetPreparedDocumentAsDocxDocumentExportQueryParameters;

    return trimArrayEnd([
        'DocumentExportClient',
        'getPreparedDocumentAsDocx',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'DocumentExportClient',
        'getPreparedDocumentAsDocx',
        ...params
      ]);
  }
}
export function __getPreparedDocumentAsDocx(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.getPreparedDocumentAsDocx(
      context.queryKey[2] as string | undefined,axiosConfig    );
}

export function useGetPreparedDocumentAsDocxQuery<TSelectData = Types.FileResponse, TError = unknown>(dto: GetPreparedDocumentAsDocxDocumentExportQueryParameters, options?: Omit<UseQueryOptions<Types.FileResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;

export function useGetPreparedDocumentAsDocxQuery<TSelectData = Types.FileResponse, TError = unknown>(id?: string | undefined, options?: Omit<UseQueryOptions<Types.FileResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetPreparedDocumentAsDocxQuery<TSelectData = Types.FileResponse, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.FileResponse, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as GetPreparedDocumentAsDocxDocumentExportQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.FileResponse, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __getPreparedDocumentAsDocx(context, axiosConfig) : __getPreparedDocumentAsDocx,
    queryKey: getPreparedDocumentAsDocxQueryKey(id),
    ...getPreparedDocumentAsDocxDefaultOptions as unknown as Omit<UseQueryOptions<Types.FileResponse, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setGetPreparedDocumentAsDocxData(queryClient: QueryClient, updater: (data: Types.FileResponse | undefined) => Types.FileResponse, id?: string | undefined) {
  queryClient.setQueryData(getPreparedDocumentAsDocxQueryKey(id),
    updater
  );
}

export function setGetPreparedDocumentAsDocxDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.FileResponse | undefined) => Types.FileResponse) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function getPreparedDocumentAsRtfUrl(id?: string | undefined): string {
  let url_ = getBaseUrl() + "/api/document-export/prepared-as-rtf?";
if (id === null)
    throw new Error("The parameter 'id' cannot be null.");
else if (id !== undefined)
    url_ += "id=" + encodeURIComponent("" + id) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getPreparedDocumentAsRtfDefaultOptions: Omit<UseQueryOptions<Types.FileResponse, unknown, Types.FileResponse>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.FileResponse, unknown, Types.FileResponse>, 'queryFn'>> = {
};
export function getGetPreparedDocumentAsRtfDefaultOptions() {
  return getPreparedDocumentAsRtfDefaultOptions;
};
export function setGetPreparedDocumentAsRtfDefaultOptions(options: typeof getPreparedDocumentAsRtfDefaultOptions) {
  getPreparedDocumentAsRtfDefaultOptions = options;
}

export function getPreparedDocumentAsRtfQueryKey(id?: string | undefined): QueryKey;
export function getPreparedDocumentAsRtfQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as GetPreparedDocumentAsRtfDocumentExportQueryParameters;

    return trimArrayEnd([
        'DocumentExportClient',
        'getPreparedDocumentAsRtf',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'DocumentExportClient',
        'getPreparedDocumentAsRtf',
        ...params
      ]);
  }
}
export function __getPreparedDocumentAsRtf(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.getPreparedDocumentAsRtf(
      context.queryKey[2] as string | undefined,axiosConfig    );
}

export function useGetPreparedDocumentAsRtfQuery<TSelectData = Types.FileResponse, TError = unknown>(dto: GetPreparedDocumentAsRtfDocumentExportQueryParameters, options?: Omit<UseQueryOptions<Types.FileResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;

export function useGetPreparedDocumentAsRtfQuery<TSelectData = Types.FileResponse, TError = unknown>(id?: string | undefined, options?: Omit<UseQueryOptions<Types.FileResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetPreparedDocumentAsRtfQuery<TSelectData = Types.FileResponse, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.FileResponse, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as GetPreparedDocumentAsRtfDocumentExportQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.FileResponse, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __getPreparedDocumentAsRtf(context, axiosConfig) : __getPreparedDocumentAsRtf,
    queryKey: getPreparedDocumentAsRtfQueryKey(id),
    ...getPreparedDocumentAsRtfDefaultOptions as unknown as Omit<UseQueryOptions<Types.FileResponse, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setGetPreparedDocumentAsRtfData(queryClient: QueryClient, updater: (data: Types.FileResponse | undefined) => Types.FileResponse, id?: string | undefined) {
  queryClient.setQueryData(getPreparedDocumentAsRtfQueryKey(id),
    updater
  );
}

export function setGetPreparedDocumentAsRtfDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.FileResponse | undefined) => Types.FileResponse) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function getPreparedDocumentAsPdfUrl(id?: string | undefined): string {
  let url_ = getBaseUrl() + "/api/document-export/prepared-as-pdf?";
if (id === null)
    throw new Error("The parameter 'id' cannot be null.");
else if (id !== undefined)
    url_ += "id=" + encodeURIComponent("" + id) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function getPreparedDocumentAsPdfMutationKey(id?: string | undefined): MutationKey {
  return trimArrayEnd([
      'DocumentExportClient',
      'getPreparedDocumentAsPdf',
      id as any,
    ]);
}

export function useGetPreparedDocumentAsPdfMutation<TContext>(id?: string | undefined, options?: Omit<UseMutationOptions<Types.FileResponse, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.FileResponse, unknown, void, TContext> {
  const key = getPreparedDocumentAsPdfMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.getPreparedDocumentAsPdf(id),
    mutationKey: key,
  });
}
  
type GetPreparedDocumentAsPdf__MutationParameters = GetPreparedDocumentAsPdfDocumentExportQueryParameters

export function useGetPreparedDocumentAsPdfMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.FileResponse, unknown, GetPreparedDocumentAsPdf__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: GetPreparedDocumentAsPdfDocumentExportQueryParameters}): UseMutationResult<Types.FileResponse, unknown, GetPreparedDocumentAsPdf__MutationParameters, TContext> {
  const key = getPreparedDocumentAsPdfMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: GetPreparedDocumentAsPdf__MutationParameters) => Client.getPreparedDocumentAsPdf(data.id ?? options?.parameters?.id!),
  mutationKey: key,
});
}
  
export function getExportNameUrl(documentId: number): string {
  let url_ = getBaseUrl() + "/api/document-export/export-name/{documentId}";
if (documentId === undefined || documentId === null)
  throw new Error("The parameter 'documentId' must be defined.");
url_ = url_.replace("{documentId}", encodeURIComponent("" + documentId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getExportNameDefaultOptions: Omit<UseQueryOptions<string, unknown, string>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<string, unknown, string>, 'queryFn'>> = {
};
export function getGetExportNameDefaultOptions() {
  return getExportNameDefaultOptions;
};
export function setGetExportNameDefaultOptions(options: typeof getExportNameDefaultOptions) {
  getExportNameDefaultOptions = options;
}

export function getExportNameQueryKey(documentId: number): QueryKey;
export function getExportNameQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { documentId,  } = params[0] as GetExportNameDocumentExportQueryParameters;

    return trimArrayEnd([
        'DocumentExportClient',
        'getExportName',
        documentId as any,
      ]);
  } else {
    return trimArrayEnd([
        'DocumentExportClient',
        'getExportName',
        ...params
      ]);
  }
}
export function __getExportName(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.getExportName(
      context.queryKey[2] as number,axiosConfig    );
}

export function useGetExportNameQuery<TSelectData = string, TError = unknown>(dto: GetExportNameDocumentExportQueryParameters, options?: Omit<UseQueryOptions<string, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Get document name for export.
 */
export function useGetExportNameQuery<TSelectData = string, TError = unknown>(documentId: number, options?: Omit<UseQueryOptions<string, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetExportNameQuery<TSelectData = string, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<string, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let documentId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ documentId,  } = params[0] as GetExportNameDocumentExportQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [documentId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<string, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __getExportName(context, axiosConfig) : __getExportName,
    queryKey: getExportNameQueryKey(documentId),
    ...getExportNameDefaultOptions as unknown as Omit<UseQueryOptions<string, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Get document name for export.
 */
export function setGetExportNameData(queryClient: QueryClient, updater: (data: string | undefined) => string, documentId: number) {
  queryClient.setQueryData(getExportNameQueryKey(documentId),
    updater
  );
}

/**
 * Get document name for export.
 */
export function setGetExportNameDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: string | undefined) => string) {
  queryClient.setQueryData(queryKey, updater);
}