//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../magadan.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './SharePointWebhookClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type HandleRequestSharePointWebhookQueryParameters = {
  validationToken?: string | null | undefined ;
}

export function handleRequestUrl(validationToken?: string | null | undefined): string {
  let url_ = getBaseUrl() + "/api/spwebhooks/handle-webhook?";
if (validationToken !== undefined && validationToken !== null)
    url_ += "validationToken=" + encodeURIComponent("" + validationToken) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function handleRequestMutationKey(validationToken?: string | null | undefined): MutationKey {
  return trimArrayEnd([
      'SharePointWebhookClient',
      'handleRequest',
      validationToken as any,
    ]);
}

/**
 * Responds to requests generated by subscriptions registered with the SharePoint WebHook REST API.
Documentation: https://learn.microsoft.com/en-us/sharepoint/dev/apis/webhooks/webhooks-reference-implementation.
If a validation token is present, we need to respond within 5 seconds by
returning the given validation token. This only happens when a new web hook is being added.
 * @param validationToken (optional) Token to validate current endpoint for webhhok creating.
 * @param content (optional) Content of request.
 */
export function useHandleRequestMutation<TContext>(validationToken?: string | null | undefined, options?: Omit<UseMutationOptions<string, unknown, Types.ResponseDataOfNotificationData, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<string, unknown, Types.ResponseDataOfNotificationData, TContext> {
  const key = handleRequestMutationKey(validationToken);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (content: Types.ResponseDataOfNotificationData) => Client.handleRequest(validationToken, content),
    mutationKey: key,
  });
}
  
type HandleRequest__MutationParameters = HandleRequestSharePointWebhookQueryParameters & {
  content: Types.ResponseDataOfNotificationData;
}

/**
 * Responds to requests generated by subscriptions registered with the SharePoint WebHook REST API.
Documentation: https://learn.microsoft.com/en-us/sharepoint/dev/apis/webhooks/webhooks-reference-implementation.
If a validation token is present, we need to respond within 5 seconds by
returning the given validation token. This only happens when a new web hook is being added.
 * @param validationToken (optional) Token to validate current endpoint for webhhok creating.
 * @param content (optional) Content of request.
 */
export function useHandleRequestMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<string, unknown, HandleRequest__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: HandleRequestSharePointWebhookQueryParameters}): UseMutationResult<string, unknown, HandleRequest__MutationParameters, TContext> {
  const key = handleRequestMutationKey(options?.parameters?.validationToken!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: HandleRequest__MutationParameters) => Client.handleRequest(data.validationToken ?? options?.parameters?.validationToken!, data.content),
  mutationKey: key,
});
}