//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../magadan.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../magadan.types';
import { getAxios, getBaseUrl } from './helpers';

/**
 * Responds to requests generated by subscriptions registered with the SharePoint WebHook REST API.
Documentation: https://learn.microsoft.com/en-us/sharepoint/dev/apis/webhooks/webhooks-reference-implementation.
If a validation token is present, we need to respond within 5 seconds by
returning the given validation token. This only happens when a new web hook is being added.
 * @param validationToken (optional) Token to validate current endpoint for webhhok creating.
 * @param content (optional) Content of request.
 */
export function handleRequest(validationToken?: string | null | undefined, content?: Types.ResponseDataOfNotificationData | undefined, config?: AxiosRequestConfig | undefined): Promise<string> {
    let url_ = getBaseUrl() + "/api/spwebhooks/handle-webhook?";
    if (validationToken !== undefined && validationToken !== null)
        url_ += "validationToken=" + encodeURIComponent("" + validationToken) + "&";
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeResponseDataOfNotificationData(content);

    let options_: AxiosRequestConfig = {
        ..._requestConfigHandleRequest,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigHandleRequest?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processHandleRequest(_response);
    });
}

function processHandleRequest(response: AxiosResponse): Promise<string> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
    
        result200 = resultData200;
    
        return Promise.resolve<string>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<string>(null as any);
}
let _requestConfigHandleRequest: Partial<AxiosRequestConfig> | null;
export function getHandleRequestRequestConfig() {
  return _requestConfigHandleRequest;
}
export function setHandleRequestRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigHandleRequest = value;
}
export function patchHandleRequestRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigHandleRequest = patch(_requestConfigHandleRequest ?? {});
}