//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../magadan.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './TestDataClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';



export type FormDataTestDataMutationParameters = {
  a?: number | undefined ;
}

export function throwErrorUrl(): string {
  let url_ = getBaseUrl() + "/error-test";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let throwErrorDefaultOptions: Omit<UseQueryOptions<string, unknown, string>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<string, unknown, string>, 'queryFn'>> = {
};
export function getThrowErrorDefaultOptions() {
  return throwErrorDefaultOptions;
};
export function setThrowErrorDefaultOptions(options: typeof throwErrorDefaultOptions) {
  throwErrorDefaultOptions = options;
}

export function throwErrorQueryKey(): QueryKey;
export function throwErrorQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd([
      'TestDataClient',
      'throwError',
    ]);
}
export function __throwError(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.throwError(
axiosConfig    );
}

/**
 * Demonstrates an error response.
 */
export function useThrowErrorQuery<TSelectData = string, TError = unknown>(options?: Omit<UseQueryOptions<string, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useThrowErrorQuery<TSelectData = string, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<string, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<string, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __throwError(context, axiosConfig) : __throwError,
    queryKey: throwErrorQueryKey(),
    ...throwErrorDefaultOptions as unknown as Omit<UseQueryOptions<string, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Demonstrates an error response.
 */
export function setThrowErrorData(queryClient: QueryClient, updater: (data: string | undefined) => string, ) {
  queryClient.setQueryData(throwErrorQueryKey(),
    updater
  );
}

/**
 * Demonstrates an error response.
 */
export function setThrowErrorDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: string | undefined) => string) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function sendEmailUrl(): string {
  let url_ = getBaseUrl() + "/send-email";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function sendEmailMutationKey(): MutationKey {
  return trimArrayEnd([
      'TestDataClient',
      'sendEmail',
    ]);
}

/**
 * Sends a dummy email
 */
export function useSendEmailMutation<TContext>(options?: Omit<UseMutationOptions<string, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<string, unknown, void, TContext> {
  const key = sendEmailMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.sendEmail(),
    mutationKey: key,
  });
}
  
export function patchUrl(): string {
  let url_ = getBaseUrl() + "/patch";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function patchMutationKey(): MutationKey {
  return trimArrayEnd([
      'TestDataClient',
      'patch',
    ]);
}

/**
 * Tests RequiredOrUndefined attribute
 */
export function usePatchMutation<TContext>(options?: Omit<UseMutationOptions<string, unknown, Types.TestPatchDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<string, unknown, Types.TestPatchDto, TContext> {
  const key = patchMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.TestPatchDto) => Client.patch(dto),
    mutationKey: key,
  });
}
  
export function formDataUrl(): string {
  let url_ = getBaseUrl() + "/formdata";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function formDataMutationKey(): MutationKey {
  return trimArrayEnd([
      'TestDataClient',
      'formData',
    ]);
}

/**
 * Try this in browser with language set to DE
 * @param a (optional) 
 */
export function useFormDataMutation<TContext>(options?: Omit<UseMutationOptions<string, unknown, FormDataTestDataMutationParameters, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<string, unknown, FormDataTestDataMutationParameters, TContext> {
  const key = formDataMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (formDataTestDataMutationParameters: FormDataTestDataMutationParameters) => Client.formData(formDataTestDataMutationParameters.a),
    mutationKey: key,
  });
}